### PR TITLE
Upgrade workbench public. Version to 55 after CLCO

### PR DESCRIPTION
**Pull request by GermanMaly**

### CODE REVIEW

**Comment by estrudels** [comment]
I hope that this will available soon and merged! 🥳

**Comment by jonnyhork** [comment]
@estrudels Oh so sorry, I forgot to merge it!

**Comment by estrudels** [comment]
@jonnyhork Thanks for merging it in 😀

I am curious when will the changes be propagated to [SF - Workbench](https://workbench.developerforce.com/login.php)

Currently the latest Salesforce API Version I can select is **v54**, when could I expect the changes to be visible.

I appreciate the quick feedback loop you guys have 🥰

Thanks

Workbench-Cooked

**Comment by jonnyhork** [comment]
@estrudels I need to promote the changes to prod but need to dust off some stuff here before I can. Should be out soon!

**Comment by estrudels** [comment]
@jonnyhork Of course sounds good, thanks for the update! 😊

On a side note I noticed that this GitHub ([forceworkbench](https://github.com/forceworkbench/forceworkbench)) does not have an **Issues** tab

Is there any plan to add the **Issues** tab so the community can we report problems or not the process your team follows

Currently I asked a question in **Salesforce Stack Exchange** about this SF Force Work Bench API issue, and was directed to this Pull Request

[SF Workbench - API Version - v55 Not Appearing](https://salesforce.stackexchange.com/questions/381303/sf-workbench-api-version-v55-not-appearing)

What avenue do you suggest to report issues?

Thanks

**Comment by jonnyhork** [comment]
@estrudels Sorry to say, but workbench has been in maintenance mode for a while now actually and is not actively supported. At this time we are only keeping the lights on and updating the API version when someone submits a PR.

The recommendation is to run Workbench locally or fork the repo and host it yourself. Instructions can be found in the [README.md](https://github.com/forceworkbench/forceworkbench#readme)

**Comment by jonnyhork** [comment]
@estrudels v55 should be available now for you at https://workbench.developerforce.com/login.php

**Comment by estrudels** [comment]
@jonnyhork Thanks for all the information, thanks for the update and I confirm that I am able to select **v55** now! 😃

**Pull request merged**
